import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";
import Header from "./ui/header/header";
import Footer from "./ui/footer/footer";
import AOSProvider from "./AOSProvider";
import CursorTrailCanvas from "./ui/cursor-trail-canvas";

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html data-theme="light" lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased bg-base-100`}
      >
        <AOSProvider>
          <Header />
          <CursorTrailCanvas className="top-0 left-0 pointer-events-none fixed inset-0 z-50 h-full w-full" />
          {children}
          <Footer />
        </AOSProvider>
      </body>
    </html>
  );
}
